// Datos de ejemplo para pruebas
// Copiar esta estructura a tu Google Sheet

export const SAMPLE_INVITATIONS = [
  {
    id: 'inv-001',
    nombre: 'Juan García',
    email: 'juan@example.com',
    telefono: '+34 600 123 456',
    token: 'juan-garcia-token-123',
    rsvp: 'pendiente',
    fechaConfirmacion: null,
    numPersonas: 1,
    notas: 'Sin restricciones dietéticas',
    fechaEnvio: '2026-06-01',
  },
  {
    id: 'inv-002',
    nombre: 'María López',
    email: 'maria@example.com',
    telefono: '+34 600 234 567',
    token: 'maria-lopez-token-456',
    rsvp: 'pendiente',
    fechaConfirmacion: null,
    numPersonas: 2,
    notas: 'Vegetariana',
    fechaEnvio: '2026-06-01',
  },
  {
    id: 'inv-003',
    nombre: 'Carlos Rodríguez',
    email: 'carlos@example.com',
    telefono: '+34 600 345 678',
    token: 'carlos-rodriguez-token-789',
    rsvp: 'pendiente',
    fechaConfirmacion: null,
    numPersonas: 1,
    notas: 'Sin gluten',
    fechaEnvio: '2026-06-01',
  },
  {
    id: 'inv-004',
    nombre: 'Ana Martínez',
    email: 'ana@example.com',
    telefono: '+34 600 456 789',
    token: 'ana-martinez-token-101',
    rsvp: 'confirmado',
    fechaConfirmacion: '2026-06-15',
    numPersonas: 2,
    notas: 'Alérgica a frutos secos',
    fechaEnvio: '2026-06-01',
  },
  {
    id: 'inv-005',
    nombre: 'Pedro Sánchez',
    email: 'pedro@example.com',
    telefono: '+34 600 567 890',
    token: 'pedro-sanchez-token-202',
    rsvp: 'rechazado',
    fechaConfirmacion: '2026-06-10',
    numPersonas: 0,
    notas: 'No puede asistir por trabajo',
    fechaEnvio: '2026-06-01',
  },
];

export const SHEET_HEADERS = [
  'ID',
  'Nombre',
  'Email',
  'Teléfono',
  'Token',
  'RSVP',
  'Fecha Confirmación',
  'Número de Personas',
  'Notas',
  'Fecha Envío',
];
