// Datos de ejemplo para pruebas
// Copiar esta estructura a tu Google Sheet

export const SAMPLE_INVITATIONS = [
  {
    id: 'inv-001',
    nombre: 'Juan García',
    group: 'García',
    email: 'juan@example.com',
    telefono: '+34 600 123 456',
    token: 'ec67bd8ff54d',
    rsvp: 'pendiente',
    fechaConfirmacion: null,
    numPersonas: 1,
    notas: 'Sin restricciones dietéticas',
    fechaEnvio: '2026-06-01',
  },
  {
    id: 'inv-006',
    nombre: 'Lucía García',
    group: 'García',
    email: 'lucia.garcia@example.com',
    telefono: '+34 600 111 222',
    token: 'ec67bd8ff54d',
    rsvp: 'pendiente',
    fechaConfirmacion: null,
    numPersonas: 1,
    notas: 'Vegetariana',
    fechaEnvio: '2026-06-01',
  },
  {
    id: 'inv-007',
    nombre: 'Miguel García',
    group: 'García',
    email: 'miguel.garcia@example.com',
    telefono: '+34 600 222 333',
    token: 'ec67bd8ff54d',
    rsvp: 'pendiente',
    fechaConfirmacion: null,
    numPersonas: 2,
    notas: 'Sin gluten',
    fechaEnvio: '2026-06-01',
  },
  {
    id: 'inv-008',
    nombre: 'Sofía García',
    group: 'García',
    email: 'sofia.garcia@example.com',
    telefono: '+34 600 333 444',
    token: 'ec67bd8ff54d',
    rsvp: 'pendiente',
    fechaConfirmacion: null,
    numPersonas: 1,
    notas: 'Alérgica a frutos secos',
    fechaEnvio: '2026-06-01',
  },
  {
    id: 'inv-002',
    nombre: 'María López',
    group: 'López',
    email: 'maria@example.com',
    telefono: '+34 600 234 567',
    token: '30070e109464',
    rsvp: 'pendiente',
    fechaConfirmacion: null,
    numPersonas: 2,
    notas: 'Vegetariana',
    fechaEnvio: '2026-06-01',
  },
  {
    id: 'inv-003',
    nombre: 'Carlos Rodríguez',
    group: 'Rodríguez',
    email: 'carlos@example.com',
    telefono: '+34 600 345 678',
    token: 'ad708010558e',
    rsvp: 'pendiente',
    fechaConfirmacion: null,
    numPersonas: 1,
    notas: 'Sin gluten',
    fechaEnvio: '2026-06-01',
  },
  {
    id: 'inv-004',
    nombre: 'Ana Martínez',
    group: 'Martínez',
    email: 'ana@example.com',
    telefono: '+34 600 456 789',
    token: 'd81498fc63c0',
    rsvp: 'confirmado',
    fechaConfirmacion: '2026-06-15',
    numPersonas: 2,
    notas: 'Alérgica a frutos secos',
    fechaEnvio: '2026-06-01',
  },
  {
    id: 'inv-005',
    nombre: 'Pedro Sánchez',
    group: 'Sánchez',
    email: 'pedro@example.com',
    telefono: '+34 600 567 890',
    token: '2bd1d3d69584',
    rsvp: 'rechazado',
    fechaConfirmacion: '2026-06-10',
    numPersonas: 0,
    notas: 'No puede asistir por trabajo',
    fechaEnvio: '2026-06-01',
  },
];

export const SHEET_HEADERS = [
  'ID',
  'Nombre',
  'Email',
  'Teléfono',
  'Token',
  'RSVP',
  'Fecha Confirmación',
  'Número de Personas',
  'Notas',
  'Fecha Envío',
];
